### ISSUE TITLE
add custom operation

### ISSUE THREAD

**Issue by chenyuxin1999** [marcovirgolin/genepro#3]
Hi,
It is amazing to experiment with this wonderful code. And I wonder what can I do if I want to add custom operation like relu or sign into operation set? Any suggestion is appreciated :)

**Comment by marcovirgolin** [comment]
Hi, 

Terribly sorry for the late reply, I somehow did not notice the issue.

It suffices to extend the `Node` class similarly to how it is done in the file `genepro/node_impl.py`.

For example,

```python
class ReLU(Node):
  def __init__(self):
    super(ReLU,self).__init__()
    self.arity = 1 # this function takes a single argument
    self.symb = 'relu'

  def _get_args_repr(self, args):
    return self._get_typical_repr(args,'before')

  def get_output(self, X):
    child_output = self._get_child_outputs(X)[0] # the argument for this function is the output of the single child node
    return np.clip(child_output, 0, None)
```
