### ISSUE TITLE
Parsing of features fails.

### ISSUE THREAD

**Issue by giorgia-nadizar** [marcovirgolin/genepro#4]
The parsing of features fails due to wrong substring index here: https://github.com/marcovirgolin/genepro/blob/0ba5371c6c36fe5e9081762866bdcdb040c021ec/genepro/util.py#L81
Works smoothly with [2:] instead of [1:].

**Comment by marcovirgolin** [comment]
Oh, right! Do you want to make a PR or prefer me to push it?
